name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: [8.0.x, 9.0.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore src/Sharpflake.csproj

      - name: Build
        run: dotnet build src/Sharpflake/Sharpflake.csproj --configuration Release --no-restore

      - name: Pack
        run: dotnet pack src/Sharpflake/Sharpflake.csproj --configuration Release --no-build -o ./packages

      - name: Publish to NuGet
        if: github.event.action == 'created'
        run: dotnet nuget push ./packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

      - name: Publish to GitHub Packages
        if: github.event.action == 'created'
        run: dotnet nuget push ./packages/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/PedroCavaleiro/index.json
